/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.anurag.navigatingtheskies.gui;

import com.anurag.navigatingtheskies.Database.FlightDAO;
import com.anurag.navigatingtheskies.Database.PassengerDAO;
import com.anurag.navigatingtheskies.Database.TicketDAO;
import com.anurag.navigatingtheskies.models.Flight;
import com.anurag.navigatingtheskies.models.Passenger;
import com.anurag.navigatingtheskies.models.Ticket;
import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author guler
 */
public class BookingPage extends javax.swing.JFrame {

    /**
     * Creates new form BookingPage
     */
    private static String flightId;
    private static String userName;
    private static Passenger passenger;
    private static Flight flight;
    
    public BookingPage(String loggedInUserName,String flightId) {
        initComponents();
        userName = loggedInUserName;
        this.flightId = flightId;
        try {
            getDetails(userName,this.flightId);
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
        flightIdTF.setText(flight.getFlightId());
        departureDateTF.setText(flight.getDepartureDate().toString());
        arrivalDateTF.setText(flight.getArrivalDate().toString());
        departureTimeTF.setText(flight.getDepartureTime().toString());
        arrivalTimeTF.setText(flight.getArrivalTime().toString());
        SourceTF.setText(flight.getSource());
        destinationTF.setText(flight.getDestination());
        SpinnerNumberModel model = new SpinnerNumberModel(0,0,flight.getSeats(),1);
        seatsTF.setModel(model);
    }
    
    
    private void getDetails(String passengerName,String flightId) throws SQLException{
        PassengerDAO passengerDAO = new PassengerDAO();
        FlightDAO flightDAO = new FlightDAO();
        
        this.passenger = passengerDAO.fetchPassengerDetails(userName);
        this.flight = flightDAO.fetchFlightDetails(flightId);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        flightIdTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        departureDateTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        arrivalDateTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        departureTimeTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        arrivalTimeTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        SourceTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        destinationTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        seatsTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomSpinnerField();
        jLabel1 = new javax.swing.JLabel();
        amountTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        bookBtn = new com.anurag.navigatingtheskies.gui.customComponents.RButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Navigating The Skies");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/iconImage.jpg")));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Heading.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        Heading.setText("Booking Page");

        flightIdTF.setEditable(false);
        flightIdTF.setBackground(new java.awt.Color(255, 255, 255));
        flightIdTF.setLabelText("Flight Id :");

        departureDateTF.setEditable(false);
        departureDateTF.setBackground(new java.awt.Color(255, 255, 255));
        departureDateTF.setLabelText("Departure Date :");

        arrivalDateTF.setEditable(false);
        arrivalDateTF.setBackground(new java.awt.Color(255, 255, 255));
        arrivalDateTF.setLabelText("Arrival Date :");

        departureTimeTF.setEditable(false);
        departureTimeTF.setBackground(new java.awt.Color(255, 255, 255));
        departureTimeTF.setLabelText("Departure Time :");

        arrivalTimeTF.setEditable(false);
        arrivalTimeTF.setBackground(new java.awt.Color(255, 255, 255));
        arrivalTimeTF.setLabelText("Arrival Time :");

        SourceTF.setEditable(false);
        SourceTF.setBackground(new java.awt.Color(255, 255, 255));
        SourceTF.setLabelText("Source :");

        destinationTF.setEditable(false);
        destinationTF.setBackground(new java.awt.Color(255, 255, 255));
        destinationTF.setLabelText("Destination :");

        seatsTF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                seatsTFStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Number of Seats :");

        amountTF.setEditable(false);
        amountTF.setBackground(new java.awt.Color(255, 255, 255));
        amountTF.setLabelText("Amount :");

        bookBtn.setText("Confirm Booking");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flightIdTF, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(departureDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arrivalDateTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(amountTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(departureTimeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(SourceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(destinationTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(arrivalTimeTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(seatsTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SourceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seatsTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seatsTFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seatsTFStateChanged
        // TODO add your handling code here:
        int numberOfSeats = (int) seatsTF.getValue();
        int amount = flight.getPrice() * numberOfSeats;
        amountTF.setText(String.valueOf(amount));
    }//GEN-LAST:event_seatsTFStateChanged

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        if(verifyInput()){
            try {
                // TODO add your handling code here:
                TicketDAO ticketDAO = new TicketDAO();
                ticketDAO.createTicket(userName, flightIdTF.getText(), (int) seatsTF.getValue(), Integer.parseInt(amountTF.getText()));
                JOptionPane.showMessageDialog(null,"Your ticket was booked successfully","Success Message",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(BookingPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bookBtnActionPerformed

    private boolean verifyInput(){
        if((int) seatsTF.getValue()==0){
            JOptionPane.showMessageDialog(null,"Please Select the number of seats to be booked","Input error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingPage(userName,flightId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField SourceTF;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField amountTF;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField arrivalDateTF;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField arrivalTimeTF;
    private com.anurag.navigatingtheskies.gui.customComponents.RButton bookBtn;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField departureDateTF;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField departureTimeTF;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField destinationTF;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField flightIdTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomSpinnerField seatsTF;
    // End of variables declaration//GEN-END:variables
}
