/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.anurag.navigatingtheskies.gui;
import java.awt.Color;
import javax.swing.JOptionPane;
import com.anurag.navigatingtheskies.Database.PassengerDAO;
import com.anurag.navigatingtheskies.models.Passenger;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author guler
 */
public class LoginPage extends javax.swing.JFrame {
      
    /**
     * Creates new form welcomePage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomTextField();
        passwordTF = new com.anurag.navigatingtheskies.gui.customComponents.CustomPasswordField();
        loginBtn = new com.anurag.navigatingtheskies.gui.customComponents.RButton();
        jLabel1 = new javax.swing.JLabel();
        signupBtn = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        bgFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Navigating The Skies");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/iconImage.jpg")));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTF.setLabelText("Username :");
        usernameTF.setOpaque(true);
        getContentPane().add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 180, -1));

        passwordTF.setLabelText("Password :");
        getContentPane().add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 180, -1));

        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 100, 50));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Not a registered user ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        signupBtn.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(102, 255, 255));
        signupBtn.setText("Sign Up");
        signupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupBtnMouseExited(evt);
            }
        });
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        bgFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SplashImage.jpg"))); // NOI18N
        getContentPane().add(bgFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtnMouseEntered
        // TODO add your handling code here:
        signupBtn.setForeground(new Color(102,255,204));
    }//GEN-LAST:event_signupBtnMouseEntered

    private void signupBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtnMouseExited
        // TODO add your handling code here:
        signupBtn.setForeground(new Color(102,255,255));
    }//GEN-LAST:event_signupBtnMouseExited

    private void signupBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new SignUpPage().setVisible(true);
    }//GEN-LAST:event_signupBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new welcomePage().setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
        String userName = usernameTF.getText();
        char[] passChar = passwordTF.getPassword();
        String pass = new String(passChar);
        if(userName.isEmpty() || pass.length()==0){
            JOptionPane.showMessageDialog(null,"Username/Password cannot be empty","Alert",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {    
            PassengerDAO passengerDAO = new PassengerDAO();
            
            String hashedPass = passengerDAO.fetchHashedPass(userName);
            boolean loginSuccess = false;
            
            if(hashedPass!=null){
                loginSuccess = BCrypt.checkpw(pass, hashedPass);
            }
            
            if(loginSuccess){
                passengerDAO.updateLoginDate(userName);
                JOptionPane.showMessageDialog(null, "Login Successfull");
         
                this.dispose();
                new HomePage(userName).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Wrong Username/Password","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_loginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel bgFrame;
    private javax.swing.JLabel jLabel1;
    private com.anurag.navigatingtheskies.gui.customComponents.RButton loginBtn;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomPasswordField passwordTF;
    private javax.swing.JLabel signupBtn;
    private com.anurag.navigatingtheskies.gui.customComponents.CustomTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
